### ISSUE TITLE
unsubscribing firestore snapshot after syncDocument/syncCollection?

### ISSUE THREAD

**Issue by NickFranceschina** [n6g7/redux-saga-firebase#92] opened 2018-01-04 16:13 UTC
how do I get ahold of the `unsubscribe()` from `syncCollection`?  when I log out of my app, I get a permissions error from the snapshot... perhaps I'm doing something wrong?

https://firebase.google.com/docs/firestore/query-data/listen

**Comment by n6g7** [comment] 2018-01-04 21:43
Hi @NickFranceschina,

The `unsubscribe` function (as mentioned in the ["Detach a listener"](https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener) section of the docs you linked to) is already handled by the [`firestore.channel`](https://github.com/n6g7/redux-saga-firebase/blob/master/src/firestore.js#L11-L21) method of rsf (which is used internally by `firestore.syncCollection`). So you shouldn't need to worry about it.

It sounds like the channel isn't being closed properly when the user logs out, are you sure your sync saga is cancelled upon logout? If so, can you share a code example reproducing your problem?

**Comment by NickFranceschina** [comment] 2018-01-09 07:27
@n6g7 thanks for your reply.  I'm probably not thinking of things correctly... when the code comes to this line:

```
console.log('syncing')
yield rsf.firestore.syncCollection(query, { successActionCreator: (snap) => actions.syncClients(snap2pojo(snap)) });`
console.log('synced')
```

it blocks on the `yield`... meaning the second `console.log` is never reached... and then later on when I log out with

`yield call(rsf.auth.signOut);`

I get 

```
Uncaught Error in onSnapshot: Error: Missing or insufficient permissions.
    at new FirestoreError (error.js:149)
```

the second `console.log` is never seen

So I'm sure my head isn't wrapped around these concepts correctly yet... any help is greatly appreciated!

**Comment by n6g7** [comment] 2018-01-11 13:24
Hey Nick,

> This has turned into a very long response, sorry about that! I realised when I started writing it that I had answered similar questions before so I tried to be exhaustive this time, hoping I could point to it later. I should probably turn this into a blog post at some point...
> Anyway, hope that will help! :)

I think this is the issue:

When you do:
```js
yield rsf.firestore.syncCollection(...)
```
redux-saga will wait for the `firestore.syncCollection` generator to finish its execution before returning control. And since the sync methods include a `while(true)` loop, execution never finishes and you never see the second `console.log`.
There is also no way to tell redux-saga to stop the execution of the `firestore.syncCollection` generator, so it never stops. This is why you see an error when the user logs out: this generator is still running but the current user (`null`) doesn't have permissions to read the data, and so the sync method fails.

## Finding a solution

As always with redux-saga it's helpful to think of sagas as processes, and to understand [the difference between fork and exec](https://en.wikipedia.org/wiki/Fork%E2%80%93exec) (if you're not familiar with these concepts already I suggest you read this wiki entry before continuing with this post).

### First problem: getting to the second `console.log`

In this case, we're "exec"-ing the `firestore.syncCollection` process, meaning we'll wait for it to finish before reaching the next instruction.
This isn't what we actually want, what we want is to start `firestore.syncCollection` "in the background", without stopping the current process (saga). That way you get back control as soon as this new saga starts and you'll see the second `console.log` call.

The way to do that in redux-saga is with the [`fork` effect creator](https://redux-saga.js.org/docs/api/):
```js
console.log('syncing')
yield fork(
  rsf.firestore.syncCollection,
  query,
  { successActionCreator: (snap) => actions.syncClients(snap2pojo(snap)) }
)
console.log('synced')
```

This tells redux-saga which saga (process) to start, how to start it (notice the `firestore.syncCollection` arguments are passed to `fork`) but **it doesn't actually start the saga**. That way redux-saga is free to start the forked saga in a different "process" and gives us back control immediately.

Using `fork` has another advantage...

### Second problem: the permissions error

... when yielded, it returns a [Task](https://redux-saga.js.org/docs/api/#task) object.
```js
const task = yield fork(rsf.firestore.syncCollection, ...)
```
This task object describes the saga that was just forked and enables you to control it (and especially to stop it!). Using the [`cancel` effect creator](https://redux-saga.js.org/docs/api/#cancel) we can tell redux-saga to stop a previously-forked saga:
```js
// Start the sync saga
const task = yield fork(rsf.firestore.syncCollection, ...)

// [...]

// Stop the sync saga
yield cancel(task)
```

This is how we're going to solve this permission error. Since the problem is that the syncing saga continues running after a user has logged out, we need to tell redux-saga to stop it!

The next question is: how do we know that the user has logged out? Well, this depends on your application so I'm going to assume you have some sort of "LOGOUT" action.
Now what we need to do is:
- start the sync saga
- wait for a logout action
- stop the sync saga

Which looks like this:
```js
function * syncForCurrentUser () {
  // Start the sync saga
  const task = yield fork(rsf.firestore.syncCollection, ...)

  // Wait for user logout
  yield take('LOGOUT')

  // Stop the sync saga
  yield cancel(task)
}
```

And that's it!
Now you also need to make sure that this `syncForCurrentUser` (or whatever you decide to call it) is restarted everytime a user logs in. To do this you can use the [`takeEvery` effect creator](https://redux-saga.js.org/docs/api/#takeEvery).

Finally, all of this could be refactored to use the [`takeLatest` effect creator](https://redux-saga.js.org/docs/api/#takeLatest), which would remove the need to manually stop the saga when a user logs out. I'll leave you to the docs to figure out how to do that.

## Effects

Hopefully, you've noticed throughout this explanation that using effects (and effect creators) is the way to go when using sagas. They enable you to use all the powerful tools built into redux-saga.

Specifically, they have two big advantages:
- they give much better control of the sagas you start/stop/fork, etc. I mean there's no easy way to fork a generator in es6 and this is the whole point of redux-saga.
- effects only *describe* what needs to be done but don't actually *do* anything. Only when redux-saga gets the effect then it instantiates your saga (it basically means you never have to, and never should call your sagas manually, i.e. `yield fork(rsf.firestore.syncCollection('items'))` is a big no-no).
  This is a *big* help when writing tests, I'll point you to the [testing docs](https://redux-saga.js.org/docs/advanced/Testing.html) on the redux-sagas website.

On a final note, if you really wanted to wait for a saga to complete before getting back control you would use the [`call` effect creator](https://redux-saga.js.org/docs/api/#call).
```js
console.log('syncing')
yield call(
  rsf.firestore.syncCollection,
  query,
  { successActionCreator: (snap) => actions.syncClients(snap2pojo(snap)) }
)
console.log('synced')
```
This would be equivalent to the code you had, only much easier to test! 😉

**Comment by NickFranceschina** [comment] 2018-01-11 17:12
Oh wow... thank you @n6g7 for this thorough explanation!  I see what's going on now, and should be able to make it work.  

So then for final clarification:  let's say I have the canonical TODO app running, but I have multiple TODO lists.  When I choose one of those lists (collections), I want to sync that list for the display component.  Now every time I switch to a different list, I need to manage all of this syncing/tasks/canceling?  What would happen if I just kept calling `syncCollection` every time I change TODO lists?  Would it just keep creating new channels to listen for collection changes?   

I understand this is a wrapper around channels... so I'm going to need to go and dig deeper into firebase's implementation so I can understand better

Thanks again!!

**Comment by n6g7** [comment] 2018-01-11 22:01
> Now every time I switch to a different list, I need to manage all of this syncing/tasks/canceling?

Yes, you would have to, although there are shortcuts which make this fairly simple (that's the point of this lib!).

> What would happen if I just kept calling syncCollection every time I change TODO lists? Would it just keep creating new channels to listen for collection changes?

If you keep forking syncCollection every time you change list without stopping previous sagas, you will be syncing multiple lists in parallel. This is perfectly valid and shouldn't create any errors, but that's probably not what you want.

Using the `takeLatest` effect creator makes all of this much simpler to write because it automatically cancels the previously forked saga (I suggest you read redux-saga's [fork model](https://redux-saga.js.org/docs/advanced/ForkModel.html) and [concurrency](https://redux-saga.js.org/docs/advanced/Concurrency.html) docs about this). Using it would look like this:

```js
/* Assuming this is the action dispatched when changing list:
 * {
 *   type: "CHANGE_LIST",
 *   listId: 123
 * }
 */

function * syncList (action) {
  yield fork(
    rsf.firestore.syncCollection,
    `lists/${action.listId}`
  )
}

// Every time a "CHANGE_LIST" action is dispatched, stop the previous sync saga and start a new one with the new action.
function * rootSaga () {
  yield takeLatest(
    'CHANGE_LIST',
    syncList
  )
}
```

**Comment by n6g7** [comment] 2018-01-27 16:38
@NickFranceschina I'm closing this for now, let me know if you have any more questions.

**Closed by n6g7** 2018-01-27 16:38 UTC
Labels: category:lib, prio:medium, question

**Comment by elitan** [comment] 2018-02-23 07:46
This thread is super helpful. Thanks! Might consider putting it in the docs.

**Comment by elitan** [comment] 2018-02-26 08:45
Really good! Will help developer in the future for sure!

**Comment by NickFranceschina** [comment] 2018-02-28 07:10
yes looks great @n6g7 !  I don't think I could have figured it out without your help!
