### ISSUE TITLE
uncaught exception when path does not exist

### ISSUE THREAD

**Issue by alfonsodev** [n6g7/redux-saga-firebase#101] opened 2018-02-15 13:25 UTC
working on react-native and react-native-firebase, 
everything works pretty well, but I found this use case, 
I'm not sure how it behaves on the web, but in react-native, you get an 
uncaught exception when using `databaes.read` with a path that doesn't exist.
The reason is that `result.val()` is not a function if `result.exists()` is false.

I did open [a pull request](https://github.com/n6g7/redux-saga-firebase/pull/100/files)
with the changes so that if the path doesn't exist read returns null. 
Alternatively, if you still want to produce an exception I'd then specify the error, 
so we can handle properly the case.

**Comment by n6g7** [comment] 2018-02-15 16:27
Hi Alfonso,

Thanks for bringing this up, that's an interesting issue. :)

About [`firebase.database.DataSnapshot#val`](https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#val) Firebase's docs states that:
> It may also return null, indicating that the DataSnapshot is empty (contains no data).

and for [`firebase.database.DataSnapshot#exists`](https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#exists) it says:
> It is slightly more efficient than using snapshot.val() !== null.

So it sounds like we should be able to call `.val()` on an empty snapshot and get `null` back.

Before we decide on a solution to your problem (and maybe merge your PR), I'd like to understand why this is happening.
I'll try to reproduce that on the web, I've never used RSF on RN but I don't think it would change anything (you're using the [JS SDK](https://firebase.google.com/docs/web/setup), right?).

Could you also share your version numbers for RN, Firebase and RSF, please? 🙂

**Comment by n6g7** [comment] 2018-02-15 16:41
Ok so I do get `null` when trying to reproduce this on the web.
Can you share the relevant RN code and confirm you're using the Firebase JS SDK? I'm genuinely curious to see how you setup Firebase + RSF in general. :)

**Comment by alfonsodev** [comment] 2018-02-18 11:11
Thank you for taking your time for trying to reproduce the problem on the web side. 
I'm using `react-native-firebase` package, which is a wrapper of the native SDKs, 
but they expose the same API than the web SDK.
In my case, I'm testing on iOS platform.  
Looking at [the code that handles snapshots](https://github.com/invertase/react-native-firebase/blob/master/lib/modules/database/DataSnapshot.js#L40) it looks like 
`val()` should always exist and it should return `null` (like the web SDK) if I'm understanding correctly the code.  
So I can try to put together a small app that reproduces the issue, it might be useful also as a reference if someone wants to use this package with `react-native`.
thanks!

**Comment by n6g7** [comment] 2018-02-28 23:25
Hi @alfonsodev,

Sorry for the long silence.

I remembered that I actually did use RSF in a demo RN project a while ago. You can find the code here: https://github.com/n6g7/cat/tree/master/rn.
The setup is pretty simple: it's RN + firebase + RSF. I'm not using any other library like react-native-firebase.

I just updated the code to the latest version of Firebase + RSF and tried to [read a non-existent value](https://github.com/n6g7/cat/blob/val-null/rn/redux/sagas/messages.js#L24-L25) and everything worked as expected:

- snapshot.exists() is false
- snapshot.val() is null

So could this be due to react-native-firebase? I haven't looked its code but I will try to do that soon.
In the meantime, could you try to find if there are any other significant differences between your app and the one I linked to?

Thanks!

**Comment by n6g7** [comment] 2018-06-11 20:09
Hi @alfonsodev, did you ever get round to setting up a demo app to reproduce the bug?
Otherwise I'll assume this is a bug with react-native-firebase and close this issue. :)

**Comment by n6g7** [comment] 2018-06-13 21:18
@alfonsodev I'll close this for now, let me know if you encounter this problem again.

**Closed by n6g7** 2018-06-13 21:18 UTC
Labels: category:lib, enhancement, priority:high
