### ISSUE TITLE
Redux-saga 1.0.0 beta support?

### ISSUE THREAD

**Issue by Slapbox** [n6g7/redux-saga-firebase#112] opened 2018-06-10 23:30 UTC
Redux-saga seems unlikely to be changing much, but there are some minor changes.

1.0.0 makes debugging a whole lot easier, but it seems to conflict with this package unfortunately. Are there official plans to update this library? 

Thanks!

**Comment by n6g7** [comment] 2018-06-11 08:46
There weren't until now. :)

I definitely want this package to be compatible with redux-saga v1 when it comes out so you can count on that. In the meantime I'll investigate why the beta release doesn't work.
Can you share any error message you might have?

**Comment by Slapbox** [comment] 2018-06-11 19:06
Ah I rolled back, but I'm using Electron and actually I got no error message. It crashed my app and devtools entirely. For that reason, I can't even say 100% it's RSF that's incompatible, but based on the last line I'm able to inspect before it crashes, I suspect it's RSF.

The only change I had to make to my own code to use `Redux-Saga@1.0.0-beta.1` (besides compatibility with RSF) was to change `put.resolve` to `putResolve` and to of course include that method in my import statements.

I believe [this issue notes all the new features and breaking changes](https://github.com/redux-saga/redux-saga/issues/1478). They are remarkably limited in scope which makes me think it's probably just a handful find/replace operations and manual updates to get RSF working with `1.0.0`.

By the way, this library is amazing! Thank you very, very much for all you do!

**Comment by n6g7** [comment] 2018-06-13 21:34
@Slapbox I can confirm that the example app breaks when updating to redux-saga v1.0.0-beta.1, so there is an problem and it's coming from RSF. I'll look into this soon. :)

**Comment by n6g7** [comment] 2018-06-16 01:07
This one took me way down the rabbit hole ... 🤯
I merged a fix in https://github.com/n6g7/redux-saga-firebase/pull/115, it works for the example app with both v0.16.0 and v1.0.0-beta.1 of redux-saga.

@Slapbox would you mind testing your app with the latest master to confirm this has fixed it for you as well? I'll keep the issue open in the meantime.

**Comment by Slapbox** [comment] 2018-06-16 03:00
Can do! Thanks very much for making and maintaining this kick-ass library.

I'll report back hopefully by the end of the weekend.

**Comment by Slapbox** [comment] 2018-06-16 20:32
Seems to work!

Took a long time to get it working because `yarn` and `npm` are so god-awful at running post-install commands when you install from non-registry sources. I saw you bumped the version number and pushed it to npm right as I finished testing lol.

Nice work @n6g7 and thank you again. I'll keep testing throughout the day and let you know if I encounter any issues. 

PS: I'm not using Firestore at all, so if there's any problems there I'm going to miss them.

**Comment by n6g7** [comment] 2018-06-16 20:45
> I saw you bumped the version number and pushed it to npm right as I finished testing haha.

Haha sorry you had to go through the manual install process just before I did that!

Thanks again for raising this issue, I'm going to close it for now since there's no reason for firebase to be differently affected by the changes.
But don't hesitate to add more comments if you encounter any more problems.

**Closed by n6g7** 2018-06-16 20:45 UTC
